name: CI

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

permissions:
  contents: read

jobs:
  quality:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: "pip"

      - name: Install Just
        uses: extractions/setup-just@v1

      - name: Clear Python cache
        run: |
          find . -type d -name "__pycache__" -exec rm -rf {} + || true
          find . -name "*.pyc" -delete || true

      - name: Install tooling (Justfile path)
        if: ${{ hashFiles('justfile') != '' }}
        run: |
          just init

      - name: Install tooling (fallback if no Justfile)
        if: ${{ hashFiles('justfile') == '' }}
        run: |
          python -m pip install -U pip
          pip install black ruff mypy pytest

      - name: Run quality checks (Justfile path)
        if: ${{ hashFiles('justfile') != '' }}
        run: |
          just all

      - name: Run quality checks (fallback if no Justfile)
        if: ${{ hashFiles('justfile') == '' }}
        run: |
          black --check .
          ruff check .
          mypy .
          pytest -q